#!/bin/bash
# Manual migration runner for Serverpod Cloud
# This script helps you run the migration SQL directly on the database

echo "=========================================="
echo "Manual Database Migration"
echo "=========================================="
echo ""
echo "This will create the missing tables:"
echo "  - task"
echo "  - task_category"
echo "  - user_settings"
echo ""
echo "Step 1: Get database connection info"
echo "  Run: scloud db info"
echo ""
echo "Step 2: Get/reset database password"
echo "  Run: scloud db user reset-password"
echo ""
echo "Step 3: Run the migration"
echo "  Replace <password> and <host> with actual values from Step 1:"
echo ""
echo "  PGPASSWORD=<password> psql \\"
echo "    \"postgresql://<host>/default?sslmode=require\" \\"
echo "    --user postgres \\"
echo "    -f migrations/20260124083839626/migration.sql"
echo ""
echo "=========================================="
echo ""
echo "Example (replace with your actual values):"
echo "  PGPASSWORD=your_password psql \"postgresql://ep-restless-water-ag76weh3-pooler.c-2.eu-central-1.aws.neon.tech/default?sslmode=require\" --user postgres -f migrations/20260124083839626/migration.sql"
echo ""
