#!/bin/bash
# Script to verify PostgreSQL tables exist on Serverpod Cloud
# This helps diagnose if tables are missing

echo "=========================================="
echo "PostgreSQL Tables Verification"
echo "=========================================="
echo ""

# Step 1: Get database connection info
echo "Step 1: Get database connection information"
echo "  Run: scloud db info"
echo ""
echo "This will show:"
echo "  - Database host"
echo "  - Database name (usually 'default')"
echo "  - Database user (usually 'postgres')"
echo ""

# Step 2: Get database password
echo "Step 2: Get/reset database password"
echo "  Run: scloud db user reset-password"
echo ""
echo "This will generate/reset the password for database access"
echo ""

# Step 3: Connect and list tables
echo "Step 3: Connect to database and list tables"
echo ""
echo "After getting the connection info and password, run:"
echo ""
echo "PGPASSWORD=<password> psql \\"
echo "  \"postgresql://<host>/default?sslmode=require\" \\"
echo "  --user postgres \\"
echo "  -c \"SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;\""
echo ""

# Step 4: Check specific tables
echo "Step 4: Check if specific tables exist"
echo ""
echo "To check for specific tables, run:"
echo ""
echo "PGPASSWORD=<password> psql \\"
echo "  \"postgresql://<host>/default?sslmode=require\" \\"
echo "  --user postgres \\"
echo "  -c \"SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('serverpod_user_info', 'task', 'task_category', 'user_settings') ORDER BY tablename;\""
echo ""

# Step 5: Check table structure
echo "Step 5: Check table structure (if table exists)"
echo ""
echo "To see columns in a table:"
echo ""
echo "PGPASSWORD=<password> psql \\"
echo "  \"postgresql://<host>/default?sslmode=require\" \\"
echo "  --user postgres \\"
echo "  -c \"\\d serverpod_user_info\""
echo ""

echo "=========================================="
echo ""
echo "Expected Serverpod Core Tables:"
echo "  ✓ serverpod_user_info (user profiles)"
echo "  ✓ serverpod_user_image (user images)"
echo "  ✓ serverpod_auth_key (auth keys)"
echo "  ✓ serverpod_session_log (session logs)"
echo "  ✓ serverpod_cloud_storage (cloud storage)"
echo "  ✓ serverpod_cloud_storage_direct_upload (direct uploads)"
echo ""
echo "Expected Custom Tables:"
echo "  ✓ task"
echo "  ✓ task_category"
echo "  ✓ user_settings"
echo ""
echo "=========================================="
echo ""
echo "Quick Check Commands:"
echo ""
echo "# List all tables"
echo "PGPASSWORD=<password> psql \"postgresql://<host>/default?sslmode=require\" --user postgres -c \"\\dt\""
echo ""
echo "# Count rows in user_info table"
echo "PGPASSWORD=<password> psql \"postgresql://<host>/default?sslmode=require\" --user postgres -c \"SELECT COUNT(*) FROM serverpod_user_info;\""
echo ""
echo "# Check migration status"
echo "PGPASSWORD=<password> psql \"postgresql://<host>/default?sslmode=require\" --user postgres -c \"SELECT * FROM serverpod_migrations ORDER BY timestamp DESC LIMIT 10;\""
echo ""
